"""Evaluate the detector and fit the model shipped in src/model.ts.

Usage (after extract.py):

    python train.py

Reads data/defactify.csv, data/cf.csv and (optionally) data/robustness.csv,
writes results.md, ../src/model.ts and ../src/__fixtures__/reference.json.
"""
import json
import os
import subprocess

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GroupKFold
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import FunctionTransformer, PolynomialFeatures, StandardScaler

import features as F
from fixtures import FIXTURES, fixture_rgb

HERE = os.path.dirname(os.path.abspath(__file__))
FEATURES = ['pv', 'log_kurtosis', 'log_fine_coarse', 'log_residual', 'log_cross',
            'gradient_lag_corr', 'local_coherence']
TS_NAMES = ['primaryVariance', 'logKurtosis', 'logFineToCoarse', 'logResidual', 'logCross',
            'gradientCorrelation', 'localCoherence']
CLIP = 5.0
C = 0.3


def make_model():
    return make_pipeline(
        StandardScaler(),
        FunctionTransformer(lambda z: np.clip(z, -CLIP, CLIP)),
        PolynomialFeatures(2),
        StandardScaler(),
        LogisticRegression(C=C, max_iter=10000),
    )


def weights(df):
    """Every source carries equal weight within its class, and both classes carry equal weight."""
    w = 1.0 / df.groupby('source')['label'].transform('count')
    for label in (0, 1):
        w[df.label == label] /= w[df.label == label].sum()
    return w * len(df)


def fit(df):
    model = make_model()
    model.fit(df[FEATURES], df.label, logisticregression__sample_weight=weights(df))
    return model


def original_score(df):
    """The 1.0.0 scoring formula, applied to the same gradient statistics."""
    excess = np.maximum(0, np.exp(df.log_kurtosis) - 3)
    return np.clip((1 - df.pv) * 0.6 + excess * 0.4, 0, 1)


def per_source(df, p):
    rows = []
    for source, g in df.assign(p=p).groupby('source', sort=False):
        truth = g.label.iloc[0]
        correct = ((g.p >= 0.5) == (g.label == 1)).mean()
        rows.append((source, 'AI-generated' if truth else 'real', len(g), correct))
    return rows


def summary(df, p):
    table = pd.DataFrame(per_source(df, p), columns=['source', 'class', 'n', 'correct'])
    real = table[table['class'] == 'real'].correct.mean()
    fake = table[table['class'] == 'AI-generated'].correct.mean()
    return table, real, fake


def load():
    d = pd.read_csv(os.path.join(HERE, 'data/defactify.csv'))
    cf = pd.read_csv(os.path.join(HERE, 'data/cf.csv'))
    d = d[(~d['mask']) & (d.variant == 'none')]
    cf = cf[~cf['mask']]
    d['split'] = np.where(d.image_id.str.contains('test'), 'test', 'validation')
    cf['split'] = 'cf'
    data = pd.concat([d, cf], ignore_index=True)
    return data.reset_index(drop=True)


def export(model, path):
    scaler1, _, poly, scaler2, logistic = [step for _, step in model.steps]
    terms = poly.powers_
    w = logistic.coef_[0] / scaler2.scale_
    intercept = logistic.intercept_[0] - np.sum(w[1:] * scaler2.mean_[1:])
    linear = [0.0] * len(FEATURES)
    quadratic = []
    for k, powers in enumerate(terms):
        idx = [i for i, p in enumerate(powers) for _ in range(p)]
        if len(idx) == 1:
            linear[idx[0]] = w[k]
        elif len(idx) == 2:
            quadratic.append((idx[0], idx[1], w[k]))

    # Check the folded form against scikit-learn before writing it
    rng = np.random.default_rng(0)
    probe = pd.DataFrame(rng.normal(size=(500, len(FEATURES))) * scaler1.scale_ * 2 + scaler1.mean_,
                         columns=FEATURES)
    z = np.clip((probe.values - scaler1.mean_) / scaler1.scale_, -CLIP, CLIP)
    logit = intercept + z @ np.array(linear) + sum(q * z[:, i] * z[:, j] for i, j, q in quadratic)
    assert np.max(np.abs(1 / (1 + np.exp(-logit)) - model.predict_proba(probe)[:, 1])) < 1e-9

    fmt = lambda v: repr(float(v))
    lines = [
        '/**',
        ' * Detector model: quadratic logistic regression on standardised gradient features',
        ' *',
        ' * GENERATED by research/train.py. Do not edit by hand; see research/README.md for the',
        ' * training data, protocol and measured accuracy.',
        ' *',
        ' * logit = intercept + Σ linear[i]·z[i] + Σ w·z[i]·z[j] (over `quadratic` entries [i, j, w]),',
        ' * where z[i] = clamp((feature[i] − mean[i]) / scale[i], −clip, clip).',
        ' */',
        'export const MODEL = {',
        f'  features: {json.dumps(TS_NAMES)} as const,',
        f'  mean: [{", ".join(fmt(v) for v in scaler1.mean_)}],',
        f'  scale: [{", ".join(fmt(v) for v in scaler1.scale_)}],',
        f'  clip: {fmt(CLIP)},',
        f'  intercept: {fmt(intercept)},',
        f'  linear: [{", ".join(fmt(v) for v in linear)}],',
        '  quadratic: [',
        *[f'    [{i}, {j}, {fmt(q)}],' for i, j, q in quadratic],
        '  ] as [number, number, number][],',
        '};',
        '',
    ]
    with open(path, 'w') as fh:
        fh.write('\n'.join(lines))
    # Match the repository's formatting so regenerating the model gives a clean diff
    subprocess.run(['npx', 'prettier', '--write', path], cwd=os.path.join(HERE, '..'), check=False,
                   capture_output=True)


def write_fixtures(model, path):
    out = {}
    for kind in FIXTURES:
        f = F.features(F.luminance(fixture_rgb(kind)))
        row = pd.DataFrame([{k: f[k] for k in FEATURES}])
        out[kind] = {
            'features': {ts: float(f[py]) for py, ts in zip(FEATURES, TS_NAMES)},
            'probability': float(model.predict_proba(row)[:, 1][0]),
        }
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as fh:
        json.dump(out, fh, indent=2)
        fh.write('\n')


def pct(x):
    return f'{100 * x:.0f}%'


def main():
    data = load()
    report = ['# Evaluation results', '',
              'Generated by `train.py`. "Correct" is the share of images in each source that the',
              'detector labels correctly at the default threshold of 0.5.', '']

    counts = data.groupby(['source', 'label']).size().reset_index(name='n')
    report += ['## Data', '', '| Source | Class | Images |', '|---|---|---|']
    report += [f'| {r.source} | {"AI-generated" if r.label else "real"} | {r.n} |' for r in counts.itertuples()]
    report += ['', 'CommunityForensics images are counted twice: once as stored and once re-encoded as JPEG',
               '(quality 75), which matches how the Defactify images are stored.', '']

    # 1. The original 1.0.0 formula
    table, real, fake = summary(data, original_score(data))
    report += ['## Original 1.0.0 scoring formula', '',
               f'Real images correct: **{pct(real)}**, AI images correct: **{pct(fake)}** (averaged over sources).', '',
               '| Source | Class | Correct |', '|---|---|---|']
    report += [f'| {source} | {cls} | {pct(correct)} |' for source, cls, _, correct in table.values]

    # 2. Cross-validation with every source represented in training
    groups = data.dataset + ':' + data.image_id.astype(str)
    p = np.zeros(len(data))
    for train_idx, test_idx in GroupKFold(5).split(data, groups=groups):
        p[test_idx] = fit(data.iloc[train_idx]).predict_proba(data.iloc[test_idx][FEATURES])[:, 1]
    table, real, fake = summary(data, p)
    auc = roc_auc_score(data.label, p, sample_weight=weights(data))
    report += ['', '## New model: 5-fold cross-validation (sources seen in training)', '',
               f'Real images correct: **{pct(real)}**, AI images correct: **{pct(fake)}**, '
               f'balanced accuracy **{pct((real + fake) / 2)}**, source-weighted ROC AUC **{auc:.2f}**.', '',
               '| Source | Class | Correct |', '|---|---|---|']
    report += [f'| {source} | {cls} | {pct(correct)} |' for source, cls, _, correct in table.values]
    cv_summary = (real, fake, auc)

    # Calibration: how often a given score is right (sources and classes weighted equally)
    w = weights(data)
    bins = [0, 0.2, 0.4, 0.6, 0.8, 1.0000001]
    labels = ['0.0 - 0.2', '0.2 - 0.4', '0.4 - 0.6', '0.6 - 0.8', '0.8 - 1.0']
    report += ['', '### How far to trust a score', '',
               'Cross-validated scores grouped by value. "Actually AI-generated" is the weighted share of',
               'images in that range that were AI-generated, with every source and both classes weighted',
               'equally.', '',
               '| rawScore | Share of images | Actually AI-generated |', '|---|---|---|']
    band = pd.cut(p, bins, right=False, labels=labels)
    for label in labels:
        in_band = band == label
        share = w[in_band].sum() / w.sum()
        ai = (w[in_band] * data.label[in_band]).sum() / w[in_band].sum() if in_band.any() else float('nan')
        report.append(f'| {label} | {pct(share)} | {pct(ai)} |')

    # 3. Leave one source out: how the model does on a source it has never seen
    report += ['', '## New model: leave-one-source-out (sources not seen in training)', '',
               'Each row is a model trained on every other source and tested on this one. This is the',
               'best guide to how the detector behaves on cameras, editing pipelines and generators',
               'that are not in the training data.', '',
               '| Source | Class | Correct |', '|---|---|---|']
    loso = []
    for source in data.source.unique():
        held = data.source == source
        p_held = fit(data[~held]).predict_proba(data[held][FEATURES])[:, 1]
        (row,) = per_source(data[held], p_held)
        loso.append(row)
        report.append(f'| {row[0]} | {row[1]} | {pct(row[3])} |')
    loso_real = np.mean([r[3] for r in loso if r[1] == 'real'])
    loso_fake = np.mean([r[3] for r in loso if r[1] != 'real'])
    report += ['', f'Average over unseen sources: real **{pct(loso_real)}**, AI-generated **{pct(loso_fake)}**.']

    # 4. Robustness to everyday edits (model trained without the Defactify test split)
    robust_path = os.path.join(HERE, 'data/robustness.csv')
    if os.path.exists(robust_path):
        r = pd.read_csv(robust_path)
        report += ['', '## Robustness to edits', '',
                   'A model trained without the Defactify test split, applied to 1,200 of its images before',
                   'and after each edit. "Flips" is the share of verdicts that change.', '',
                   '| Edit | Real flagged as AI | AI flagged as AI | Flips |', '|---|---|---|---|']
        base_model = fit(data[data.split != 'test'])
        rr = r[~r['mask']].copy()
        rr['p'] = base_model.predict_proba(rr[FEATURES])[:, 1]
        base = rr[rr.variant == 'none'].set_index('image_id').p
        for variant in ['none', 'jpeg95', 'jpeg50', 'resize0.5', 'crop3']:
            s = rr[rr.variant == variant].set_index('image_id')
            flips = ((s.p >= 0.5) != (base.loc[s.index] >= 0.5)).mean()
            label = {'none': 'None', 'jpeg95': 'Re-save as JPEG quality 95', 'jpeg50': 'Re-save as JPEG quality 50',
                     'resize0.5': 'Resize to half size', 'crop3': 'Crop 3 px (moves the JPEG grid)'}[variant]
            report.append(f'| {label} | {pct((s.p[s.label == 0] >= 0.5).mean())} | '
                          f'{pct((s.p[s.label == 1] >= 0.5).mean())} | {pct(flips)} |')

        # 5. Excluding JPEG block boundaries (the idea behind filterCompressionArtifacts)
        rm = r[r['mask']].copy()
        masked = pd.concat([pd.read_csv(os.path.join(HERE, 'data/defactify.csv')).query('mask and variant == "none"')
                            .assign(split=lambda x: np.where(x.image_id.str.contains('test'), 'test', 'validation')),
                            pd.read_csv(os.path.join(HERE, 'data/cf.csv')).query('mask').assign(split='cf')])
        masked_model = fit(masked[masked.split != 'test'])
        rm['p'] = masked_model.predict_proba(rm[FEATURES])[:, 1]
        mbase = rm[rm.variant == 'none'].set_index('image_id').p
        crop = rm[rm.variant == 'crop3'].set_index('image_id')
        mflips = ((crop.p >= 0.5) != (mbase.loc[crop.index] >= 0.5)).mean()
        plain = rr[rr.variant == 'crop3'].set_index('image_id')
        pflips = ((plain.p >= 0.5) != (base.loc[plain.index] >= 0.5)).mean()
        report += ['', '## Excluding JPEG block boundaries', '',
                   'Dropping every gradient that straddles an 8 × 8 JPEG block boundary did not improve',
                   'accuracy, and made verdicts much less stable when an image is cropped (which moves the',
                   f'JPEG grid): {pct(mflips)} of verdicts flipped after a 3-pixel crop, against {pct(pflips)}',
                   'without the exclusion. The detector therefore does not use it.']

    with open(os.path.join(HERE, 'results.md'), 'w') as fh:
        fh.write('\n'.join(report) + '\n')

    final = fit(data)
    export(final, os.path.join(HERE, '..', 'src', 'model.ts'))
    write_fixtures(final, os.path.join(HERE, '..', 'src', '__fixtures__', 'reference.json'))
    real, fake, auc = cv_summary
    print(f'CV: real {pct(real)}, AI {pct(fake)}, AUC {auc:.3f}; unseen sources: real {pct(loso_real)}, AI {pct(loso_fake)}')
    print('Wrote results.md, src/model.ts and src/__fixtures__/reference.json')


if __name__ == '__main__':
    main()
